#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source "$HOME/.profile"

# Spaceship Theme customization
ZSH_THEME="spaceship"
SPACESHIP_PROMPT_ORDER=(
    user
    host
    dir
    git
    docker
    aws
    venv
    conda
    exec_time
    line_sep
    jobs
    exit_code
    char
)
spaceship_prompt_opened=true
SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_HOST_SHOW=always
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_PREFIX="╭─ "
SPACESHIP_CHAR_SYMBOL="╰─○ "

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder


# User configuration

# You may need to manually set your language environment
export LANG=en_US.UTF+8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# plugins
plugins=(
    docker
    docker-compose	
)


# Example aliases
alias zshconfig="mate ~/.zshrc"
alias pip=pip3

# importing .bashrc setting
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# amazon aws alexa skill setting
export ASK_DEFAULT_PROFILE="alex"
export ASK_DEFAULT_DEVICE_LOCALE="en-US"

# npm completion
source <(npm completion)

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
source "$HOME/.zpreztorc"

# Kubectl completion
source <(kubectl completion zsh)
# Openshift CLI completion
source <(oc completion zsh)

# opam configuration
test -r /Users/alex/.opam/opam-init/init.zsh && . /Users/alex/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
